const songs = [
  {
    id: 1,
    title: 'Bài này không để đi diễn',
    artist: 'Anh Tú ATus',
    artwork: require('../assets/img/img1.jpg'),
    url: require('../assets/songs/BaiNayKhongDeDiDien-AnhTuAtus-8076045.mp3'),
    favorite: false,
  },
  {
    id: 2,
    title: 'Có chơi có chịu',
    artist: 'Karik',
    artwork: require('../assets/img/co-choi-co-chiu.jpg'),
    url: require('../assets/songs/Co-Choi-Co-Chiu-Karik-Only-C.mp3'),
    favorite: false,
  },
  {
    id: 3,
    title: 'Bên trên tầng lầu',
    artist: 'Tăng Duy Tân',
    artwork: require('../assets/img/ben-tren-tang-lau.jpg'),
    url: require('../assets/songs/BenTrenTangLau-TangDuyTan-7412012.mp3'),
    favorite: false,
  },
  {
    id: 4,
    title: 'Sao cũng được',
    artist: 'Thành Đạt',
    artwork: require('../assets/img/sao-cung-duoc.jpg'),
    url: require('../assets/songs/Sao-Cung-Duoc-Thanh-Dat.mp3'),
    favorite: false,
  },
  {
    id: 5,
    title: 'Một mình có buồn không',
    artist: 'Thiều Bảo Trâm',
    artwork: require('../assets/img/mot-minh-co-buon-khong.jpg'),
    url: require('../assets/songs/MotMinhCoBuonKhong1-ThieuBaoTramLouHoang-6738011.mp3'),
    favorite: false,
  },
  {
    id: 6,
    title: 'Muộn rồi mà sao còn',
    artist: 'Sơn Tùng MTP',
    artwork: require('../assets/img/muon-roi-ma-sao-con.png'),
    url: require('../assets/songs/MuonRoiMaSaoCon-SonTungMTP-7011803.mp3'),
    favorite: false,
  },
  {
    id: 7,
    title: 'Tòng phu',
    artist: 'Keyo',
    artwork: require('../assets/img/tong-phu.jpg'),
    url: require('../assets/songs/Tong-Phu-Keyo.mp3'),
    favorite: false,
  },
  {
    id: 8,
    title: 'Waiting for you',
    artist: 'Mono',
    artwork: require('../assets/img/waiting-for-you.jpg'),
    url: require('../assets/songs/WaitingForYou-MONOOnionn-7733882.mp3'),
    favorite: false,
  },
  {
    id: 9,
    title: 'Vô lượng',
    artist: 'Masew',
    artwork: require('../assets/img/vo-luong.jpg'),
    url: require('../assets/songs/Vo-Luong-Masew-Khoi-Vu-Great.mp3'),
    favorite: false,
  },
  {
    id: 10,
    title: 'Bật tình yêu lên',
    artist: 'Hòa Minzy',
    artwork: require('../assets/img/bat-tinh-yeu-len.jpg'),
    url: require('../assets/songs/BatTinhYeuLen-TangDuyTanHoaMinzy-8715666.mp3'),
    favorite: false,
  },
  // {
  //   id: 11,
  //   title: 'Em đồng ý',
  //   artist: 'Đức Phúc',
  //   artwork: require('../assets/img/em-dong-y.jpg'),
  //   url: require('../assets/songs/EmDongYIDo-DucPhucx911-9034315.mp3'),
  //   favorite: false,
  // },
  // {
  //   id: 12,
  //   title: 'Hãy trao cho anh',
  //   artist: 'Sơn Tùng MTP',
  //   artwork: require('../assets/img/hay-trao-cho-anh.jpg'),
  //   url: require('../assets/songs/HayTraoChoAnh-SonTungMTPSnoopDogg-6010660.mp3'),
  //   favorite: false,
  // },
  // {
  //   id: 13,
  //   title: 'Rồi ta sẽ ngắm pháo hoa',
  //   artist: 'Olew',
  //   artwork: require('../assets/img/roi-ta-se-ngam-phao-hoa.jpg'),
  //   url: require('../assets/songs/RoiTaSeNgamPhaoHoaCungNhau-OlewVietNam-8485329.mp3'),
  //   favorite: false,
  // },
  // {
  //   id: 14,
  //   title: 'See tình',
  //   artist: 'Hoàng Thùy Linh',
  //   artwork: require('../assets/img/see-tinh.jpg'),
  //   url: require('../assets/songs/SeeTinh-HoangThuyLinh-7702265.mp3'),
  //   favorite: false,
  // },
  // {
  //   id: 15,
  //   title: 'Yêu 5',
  //   artist: 'Rhymastic',
  //   artwork: require('../assets/img/yeu-5.jpg'),
  //   url: require('../assets/songs/Yeu5-Rhymastic-4756973.mp3'),
  //   favorite: false,
  // },
];

export default songs;
